/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2017-12-27 07:54:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html.pages.input;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class inputList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<c:import url=\"../htmlframe/headerFrame.jsp\" />\r\n");
      out.write("<c:import url=\"../htmlframe/headFrame.jsp\" />\r\n");
      out.write("<body class=\"skin-blue\">\r\n");
      out.write("<!-- header logo: style can be found in header.less -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrapper row-offcanvas row-offcanvas-left\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Right side column. Contains the navbar and content of the page -->\r\n");
      out.write("    <aside class=\"right-side\">\r\n");
      out.write("    <!-- Content Header (Page header) -->\r\n");
      out.write("            <section class=\"content-header\">\r\n");
      out.write("                <h1>\r\n");
      out.write("                    DataManagement\r\n");
      out.write("                </h1>\r\n");
      out.write("                <ol class=\"breadcrumb\">\r\n");
      out.write("                    <li><i class=\"fa fa-dashboard\"></i> Index</li>\r\n");
      out.write("                </ol>\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main content -->\r\n");
      out.write("            <section class=\"content\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <!-- collection -->\r\n");
      out.write("                        <div class=\"col-xs-12\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"nav-tabs-custom\">\r\n");
      out.write("                                <ul class=\"nav nav-tabs\">\r\n");
      out.write("                                    <div class=\"box-tools\">\r\n");
      out.write("                                        <div class=\"input-group\">\r\n");
      out.write("                                            <input type=\"text\" name=\"table_search\" id=\"table_search\" class=\"form-control input-sm pull-right\" style=\"width: 150px;\" placeholder=\"Filter\">\r\n");
      out.write("                                            <div class=\"input-group-btn\">\r\n");
      out.write("                                                <button class=\"btn btn-sm btn-default\" id=\"table_search_btn\"><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                                <div class=\"tab-content\">\r\n");
      out.write("                                    <div class=\"tab-pane active\" id=\"tab_1\">\r\n");
      out.write("                                        <table class=\"table table-hover valve-table\">\r\n");
      out.write("                                            <thead><tr>\r\n");
      out.write("                                                <th>弁番号</th>\r\n");
      out.write("                                                <th>設置プラント</th>\r\n");
      out.write("                                                <th>弁名称</th>\r\n");
      out.write("                                                <th>型式</th>\r\n");
      out.write("                                                <th>駆動方式</th>\r\n");
      out.write("                                                <th>更新日付</th>\r\n");
      out.write("                                                <th>操作</th>\r\n");
      out.write("                                            </tr></thead>\r\n");
      out.write("                                            <tbody>\r\n");
      out.write("\r\n");
      out.write("                                            </tbody>\r\n");
      out.write("                                        </table>\r\n");
      out.write("                                    </div><!-- /.tab-pane -->\r\n");
      out.write("                                </div><!-- /.tab-content -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("            </section><!-- /.content -->\r\n");
      out.write("    </aside><!-- /.right-side -->\r\n");
      out.write("</div><!-- ./wrapper -->\r\n");
      out.write("\r\n");
      out.write("<!-- add new calendar event modal -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
